name: ac_bcp47
description: BCP-47 related types with parsing, formatting, canonicalization and format validation.
version: 0.2.0
repository: https://github.com/anthochamp/dart-bcp47

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  collection: ^1.17.0
  meta: ^1.8.0
  ac_dart_essentials: ^0.2.1

dev_dependencies:
  ac_lints: ^0.2.0
  import_sorter: ^4.6.0
  test: ^1.24.2
