name: Validate & Publish

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Publish in dry-run mode without creating a GitHub Release"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/dart-validate.yml@main

  publish:
    needs: validate
    permissions:
      id-token: write
    uses: anthochamp/dev-toolbox/.github/workflows/dart-lib-publish.yml@main
    with:
      dry-run: ${{ inputs.dry-run == 'true' }}

  release:
    needs: publish
    if: ${{ inputs.dry-run != 'true' }}
    permissions:
      contents: write
    uses: anthochamp/dev-toolbox/.github/workflows/util-create-release.yml@main
    with:
      tag: ${{ needs.publish.outputs.tag }}
